### ISSUE TITLE
Thème curseur souris non pris en compte par Firefox

### ISSUE THREAD

**Issue by Meneldor** [Gaming-Linux-FR/Architect#255]
J'ai utilisé le script suite à ma réinstallation d'arch, cela simplifie beaucoup une grosse partie de la configuration initial, c'est top.
J'ai rencontré un petit soucis avec le thème breeze du curseur de la souris non pris en compte par Firefox 121, cela appliquait le thème adwaita.
Suite à l'installation de xdg-desktop-portal-gtk cela fonctionne correctement.

Solution trouvée ici : https://support.mozilla.org/fr/questions/1434500

Merci.

**Comment by Cardiacman13** [comment]
Merci je l'ai ajouté pour tout le monde : https://github.com/Gaming-Linux-FR/Architect/commit/1aca8e8b86e97fc34ac8ee4cbc250f441a2db968
