### ISSUE TITLE
Multiple errors when running the script

### ISSUE THREAD

**Issue by roxfr** [Gaming-Linux-FR/Architect#266]
Hello,
The script does not work, it stops at line 22 of the cmd.sh file.
See image below.
Regards,
Roxfr

![Bug_exec_primitive_speciale_script_architect](https://github.com/Gaming-Linux-FR/Architect/assets/52124613/ee95d775-56a4-47a5-8d78-fba0dd0c056b)

**Comment by roxfr** [comment]
cmd.sh
line 14: rename function "exec" by "execute"

grub-btrfs.sh
line 1: rename function "grub-btrfs" by "grub_btrfs"

**Comment by roxfr** [comment]
cmd.sh
line 30: see image below

![Architect_02](https://github.com/Gaming-Linux-FR/Architect/assets/52124613/e3f29c2e-516d-4bf5-bba4-a71e5eb68146)

**Comment by roxfr** [comment]
![image](https://github.com/Gaming-Linux-FR/Architect/assets/52124613/caa7e5e5-8136-4771-b73f-5ac90ed3e216)

**Comment by Cardiacman13** [comment]
![test](https://github.com/Gaming-Linux-FR/Architect/assets/83916775/58be9144-60f5-4402-bd53-82538a0ab206)

**Comment by roxfr** [comment]
Yes I made a mistake, you have to launch the script with the correct command:
`./architect.sh`
and not with:
`sh architect.sh` OR `sh ./architect.sh`
Thanks
Regards,
Roxfr
